version: 0.0
os: linux
files:
  - source: /
    destination: /tmp/cd-new-openstates.org
hooks:
  BeforeInstall:
    - location: ansible/before-install.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/after-install.sh
      timeout: 300
      runas: root
